<a href="https://colab.research.google.com/github/Satyam-Mittal2527/Deep_Learning_Concepts/blob/main/HyperParameterTuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("diabetes.csv")

In [ ]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [ ]:
X = df.drop(columns=['Outcome']).values
y = df['Outcome'].values

In [ ]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()

In [ ]:
X = scaler.fit_transform(X)

In [ ]:
X.shape

(768, 8)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=1)

In [ ]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,Dropout

In [ ]:
model = Sequential()
model.add(Dense(32, activation='relu', input_dim=8))
model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.compile(optimizer='Adam', loss= 'binary_crossentropy', metrics=['accuracy'])

In [ ]:
model.fit(X_train,y_train, batch_size=32,epochs=100,validation_data=(X_test,y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.4176 - loss: 0.7887 - val_accuracy: 0.4935 - val_loss: 0.7405
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4947 - loss: 0.7233 - val_accuracy: 0.5584 - val_loss: 0.6736
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5785 - loss: 0.6659 - val_accuracy: 0.6818 - val_loss: 0.6218
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6341 - loss: 0.6425 - val_accuracy: 0.7273 - val_loss: 0.5847
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7023 - loss: 0.5897 - val_accuracy: 0.7727 - val_loss: 0.5533
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7172 - loss: 0.5538 - val_accuracy: 0.7792 - val_loss: 0.5314
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7312 - loss: 0.5445 - val_accuracy: 0.7857 - val_loss: 0.5118
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7349 - loss: 0.5322 - val_accuracy: 0.7857 - val_loss: 0.4974
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7285 - loss: 0.5226 - val_accuracy: 0.7792 - val_loss: 0.4841
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7455 - loss: 0.4996 - val_accuracy: 0.7727 - val_loss: 0.4752
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7650 - loss: 0.4890 - val_accuracy: 0.7922 - val_loss: 0.4661
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7631 - loss: 0.5002 - val_accuracy: 0.7922 - val_loss: 0.4597
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7705 - loss: 0.4647 - val_accuracy: 0.7922 - val_loss: 0.4532
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7742 - loss: 0.4722 - val_accuracy: 0.7922 - val_loss: 0.4495
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7825 - loss: 0.4833 - val_accuracy: 0.7922 - val_loss: 0.4465
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7807 - loss: 0.4563 - val_accuracy: 0.7922 - val_loss: 0.4436
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8207 - loss: 0.4400 - val_accuracy: 0.7987 - val_loss: 0.4425
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7823 - loss: 0.4566 - val_accuracy: 0.7922 - val_loss: 0.4406
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7777 - loss: 0.4662 - val_accuracy: 0.7987 - val_loss: 0.4393
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7782 - loss: 0.4531 - val_accuracy: 0.7922 - val_loss: 0.4401
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7532 - loss: 0.4884 - val_accuracy: 0.7727 - val_loss: 0.4387
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7832 - loss: 0.4608 - val_accuracy: 0.7857 - val_loss: 0.4381
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7986 - loss: 0.4370 - val_accuracy: 0.7857 - val_loss: 0.4366
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7773 - loss: 0.4631 - val_accuracy: 0.7922 - val_loss: 0.4369
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7651 - loss: 0.4550 - val_accuracy: 0.7922 - val_loss: 0.4360
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7867 - loss: 0.4491 - val_accuracy: 0.7727 - val_loss: 0.4363
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7737 - loss: 0.4484 - val_accuracy: 0.7987 - val_loss: 0.4374
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7928 - loss: 0.4381 - val_accuracy: 0.7987 - val_loss: 0.4374
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7723 - loss: 0.4641 - val_accuracy: 0.7987 - val_loss: 0.4379
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7905 - loss: 0.4279 - val_accuracy: 0.7987 - val_loss: 0.4374
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7828 - loss: 0.4364 - val_accuracy: 0.7987 - val_loss: 0.4377
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7765 - loss: 0.4431 - val_accuracy: 0.8052 - val_loss: 0.4383
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7869 - loss: 0.4362 - val_accuracy: 0.8117 - val_loss: 0.4389
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8101 - loss: 0.4154 - val_accuracy: 0.8052 - val_loss: 0.4393
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7619 - loss: 0.4615 - val_accuracy: 0.8117 - val_loss: 0.4390
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7923 - loss: 0.4354 - val_accuracy: 0.8052 - val_loss: 0.4391
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7661 - loss: 0.4628 - val_accuracy: 0.8052 - val_loss: 0.4386
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7744 - loss: 0.4430 - val_accuracy: 0.8052 - val_loss: 0.4390
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7889 - loss: 0.4388 - val_accuracy: 0.8052 - val_loss: 0.4382
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7654 - loss: 0.4719 - val_accuracy: 0.7987 - val_loss: 0.4382
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7862 - loss: 0.4463 - val_accuracy: 0.8182 - val_loss: 0.4381
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7954 - loss: 0.4224 - val_accuracy: 0.8052 - val_loss: 0.4394
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7828 - loss: 0.4239 - val_accuracy: 0.8052 - val_loss: 0.4392
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7967 - loss: 0.4319 - val_accuracy: 0.8052 - val_loss: 0.4396
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7857 - loss: 0.4446 - val_accuracy: 0.8117 - val_loss: 0.4402
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7803 - loss: 0.4451 - val_accuracy: 0.8117 - val_loss: 0.4394
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7690 - loss: 0.4573 - val_accuracy: 0.8052 - val_loss: 0.4408
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7880 - loss: 0.4602 - val_accuracy: 0.8117 - val_loss: 0.4403
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7992 - loss: 0.4168 - val_accuracy: 0.8117 - val_loss: 0.4401
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7710 - loss: 0.4561 - val_accuracy: 0.8117 - val_loss: 0.4418
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7877 - loss: 0.4328 - val_accuracy: 0.8247 - val_loss: 0.4417
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7914 - loss: 0.4219 - val_accuracy: 0.8117 - val_loss: 0.4420
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7997 - loss: 0.4180 - val_accuracy: 0.8247 - val_loss: 0.4414
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7732 - loss: 0.4327 - val_accuracy: 0.8182 - val_loss: 0.4408
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7891 - loss: 0.4154 - val_accuracy: 0.8117 - val_loss: 0.4419
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7894 - loss: 0.4193 - val_accuracy: 0.8117 - val_loss: 0.4423
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7964 - loss: 0.4377 - val_accuracy: 0.8247 - val_loss: 0.4416
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7913 - loss: 0.4372 - val_accuracy: 0.8247 - val_loss: 0.4412
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7888 - loss: 0.4375 - val_accuracy: 0.8247 - val_loss: 0.4398
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7886 - loss: 0.4416 - val_accuracy: 0.8182 - val_loss: 0.4403
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7869 - loss: 0.4433 - val_accuracy: 0.8182 - val_loss: 0.4395
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7879 - loss: 0.4506 - val_accuracy: 0.8117 - val_loss: 0.4414
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7797 - loss: 0.4256 - val_accuracy: 0.8182 - val_loss: 0.4415
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7904 - loss: 0.4402 - val_accuracy: 0.8117 - val_loss: 0.4420
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7696 - loss: 0.4458 - val_accuracy: 0.8052 - val_loss: 0.4423
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8022 - loss: 0.4088 - val_accuracy: 0.8052 - val_loss: 0.4415
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7914 - loss: 0.4333 - val_accuracy: 0.8182 - val_loss: 0.4423
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7991 - loss: 0.4056 - val_accuracy: 0.8052 - val_loss: 0.4413
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7898 - loss: 0.4167 - val_accuracy: 0.8247 - val_loss: 0.4422
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7789 - loss: 0.4445 - val_accuracy: 0.8182 - val_loss: 0.4416
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7839 - loss: 0.4189 - val_accuracy: 0.8182 - val_loss: 0.4424
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8346 - loss: 0.3840 - val_accuracy: 0.8182 - val_loss: 0.4419
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8138 - loss: 0.4157 - val_accuracy: 0.8182 - val_loss: 0.4421
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7893 - loss: 0.4149 - val_accuracy: 0.8117 - val_loss: 0.4421
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7895 - loss: 0.4206 - val_accuracy: 0.8182 - val_loss: 0.4421
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8009 - loss: 0.4142 - val_accuracy: 0.8182 - val_loss: 0.4416
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7708 - loss: 0.4437 - val_accuracy: 0.8117 - val_loss: 0.4444
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7901 - loss: 0.4292 - val_accuracy: 0.8117 - val_loss: 0.4450
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7763 - loss: 0.4352 - val_accuracy: 0.8182 - val_loss: 0.4440
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7819 - loss: 0.4377 - val_accuracy: 0.8117 - val_loss: 0.4441
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7746 - loss: 0.4608 - val_accuracy: 0.8182 - val_loss: 0.4437
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8000 - loss: 0.4107 - val_accuracy: 0.8117 - val_loss: 0.4452
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8300 - loss: 0.3792 - val_accuracy: 0.8117 - val_loss: 0.4455
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7994 - loss: 0.4042 - val_accuracy: 0.8117 - val_loss: 0.4453
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7936 - loss: 0.4275 - val_accuracy: 0.8117 - val_loss: 0.4443
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7684 - loss: 0.4374 - val_accuracy: 0.8117 - val_loss: 0.4442
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7794 - loss: 0.4318 - val_accuracy: 0.8117 - val_loss: 0.4437
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7992 - loss: 0.3922 - val_accuracy: 0.8052 - val_loss: 0.4452
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7898 - loss: 0.4247 - val_accuracy: 0.8052 - val_loss: 0.4447
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7843 - loss: 0.4232 - val_accuracy: 0.8117 - val_loss: 0.4463
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8028 - loss: 0.4065 - val_accuracy: 0.8117 - val_loss: 0.4458
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7920 - loss: 0.4300 - val_accuracy: 0.8182 - val_loss: 0.4459
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8000 - loss: 0.4145 - val_accuracy: 0.8117 - val_loss: 0.4457
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7637 - loss: 0.4439 - val_accuracy: 0.8117 - val_loss: 0.4463
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8150 - loss: 0.3826 - val_accuracy: 0.8117 - val_loss: 0.4451
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8069 - loss: 0.4191 - val_accuracy: 0.8182 - val_loss: 0.4455
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7995 - loss: 0.4037 - val_accuracy: 0.8117 - val_loss: 0.4452
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7974 - loss: 0.4065 - val_accuracy: 0.8182 - val_loss: 0.4444
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8020 - loss: 0.4005 - val_accuracy: 0.8117 - val_loss: 0.4444
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8012 - loss: 0.4021 - val_accuracy: 0.8247 - val_loss: 0.4412

In [ ]:
#How to select appropiate optimizer
#How to decide number of nodes in a layer
#Decide number of layers
#All in one model

In [ ]:
pip install -U keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.10.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.78.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.15.1)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.19.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.2.25)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 4.0 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

In [ ]:
import kerastuner as kt

/tmp/ipykernel_238/1654478174.py:1: DeprecationWarning: `import kerastuner` is deprecated, please use `import keras_tuner`.
  import kerastuner as kt

In [ ]:
def build_model(hp):

  model= Sequential()
  model.add(Dense(32,activation='relu', input_dim=8))
  model.add(Dense(1, activation='sigmoid'))

  optimizers = hp.Choice('optimizer',values=['sgd','rmsprop','adadelta'])

  model.compile(optimizer=optimizers, loss='binary_crossentropy', metrics=['accuracy'])

  return model

In [ ]:
tuner = kt.RandomSearch(build_model,
                        objective = 'val_accuracy',
                        max_trials = 5)

In [ ]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Trial 3 Complete [00h 00m 04s]
val_accuracy: 0.7142857313156128

Best val_accuracy So Far: 0.7532467246055603
Total elapsed time: 00h 00m 21s

In [ ]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [ ]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(X_train,y_train, epochs=100,initial_epoch=6, batch_size=32, validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.7327 - loss: 0.5205 - val_accuracy: 0.7662 - val_loss: 0.4819
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7776 - loss: 0.4867 - val_accuracy: 0.7662 - val_loss: 0.4743
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7533 - loss: 0.4957 - val_accuracy: 0.7727 - val_loss: 0.4699
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7744 - loss: 0.4757 - val_accuracy: 0.7662 - val_loss: 0.4673
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7325 - loss: 0.5181 - val_accuracy: 0.7792 - val_loss: 0.4635
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7907 - loss: 0.4769 - val_accuracy: 0.7857 - val_loss: 0.4612
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7695 - loss: 0.4596 - val_accuracy: 0.7857 - val_loss: 0.4599
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7756 - loss: 0.4664 - val_accuracy: 0.7922 - val_loss: 0.4605
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7606 - loss: 0.4938 - val_accuracy: 0.7922 - val_loss: 0.4610
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7950 - loss: 0.4275 - val_accuracy: 0.7857 - val_loss: 0.4608
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7773 - loss: 0.4532 - val_accuracy: 0.7857 - val_loss: 0.4595
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7588 - loss: 0.4933 - val_accuracy: 0.7792 - val_loss: 0.4598
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7681 - loss: 0.4762 - val_accuracy: 0.7792 - val_loss: 0.4609
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7583 - loss: 0.4776 - val_accuracy: 0.7792 - val_loss: 0.4614
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7781 - loss: 0.4356 - val_accuracy: 0.7792 - val_loss: 0.4612
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7983 - loss: 0.4337 - val_accuracy: 0.7727 - val_loss: 0.4615
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7984 - loss: 0.4276 - val_accuracy: 0.7662 - val_loss: 0.4617
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8017 - loss: 0.4388 - val_accuracy: 0.7662 - val_loss: 0.4628
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7874 - loss: 0.4528 - val_accuracy: 0.7662 - val_loss: 0.4626
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7693 - loss: 0.4637 - val_accuracy: 0.7662 - val_loss: 0.4623
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7906 - loss: 0.4562 - val_accuracy: 0.7727 - val_loss: 0.4632
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7680 - loss: 0.4565 - val_accuracy: 0.7727 - val_loss: 0.4632
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7754 - loss: 0.4271 - val_accuracy: 0.7727 - val_loss: 0.4622
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7359 - loss: 0.4843 - val_accuracy: 0.7792 - val_loss: 0.4616
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7771 - loss: 0.4317 - val_accuracy: 0.7792 - val_loss: 0.4627
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8078 - loss: 0.4107 - val_accuracy: 0.7857 - val_loss: 0.4624
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7667 - loss: 0.4607 - val_accuracy: 0.7857 - val_loss: 0.4639
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8042 - loss: 0.4103 - val_accuracy: 0.7857 - val_loss: 0.4645
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7890 - loss: 0.4422 - val_accuracy: 0.7857 - val_loss: 0.4638
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8077 - loss: 0.4130 - val_accuracy: 0.7857 - val_loss: 0.4649
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7831 - loss: 0.4513 - val_accuracy: 0.7922 - val_loss: 0.4643
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7901 - loss: 0.4345 - val_accuracy: 0.7857 - val_loss: 0.4643
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7716 - loss: 0.4476 - val_accuracy: 0.7857 - val_loss: 0.4651
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8006 - loss: 0.4193 - val_accuracy: 0.7922 - val_loss: 0.4644
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7559 - loss: 0.4592 - val_accuracy: 0.7922 - val_loss: 0.4652
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8155 - loss: 0.3918 - val_accuracy: 0.7922 - val_loss: 0.4654
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7704 - loss: 0.4462 - val_accuracy: 0.7922 - val_loss: 0.4659
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7537 - loss: 0.4945 - val_accuracy: 0.7922 - val_loss: 0.4666
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7690 - loss: 0.4572 - val_accuracy: 0.7857 - val_loss: 0.4682
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7855 - loss: 0.4351 - val_accuracy: 0.7857 - val_loss: 0.4682
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7602 - loss: 0.4535 - val_accuracy: 0.7857 - val_loss: 0.4684
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7766 - loss: 0.4388 - val_accuracy: 0.7857 - val_loss: 0.4684
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8019 - loss: 0.4115 - val_accuracy: 0.7922 - val_loss: 0.4677
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8012 - loss: 0.4293 - val_accuracy: 0.7922 - val_loss: 0.4680
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7870 - loss: 0.4280 - val_accuracy: 0.7987 - val_loss: 0.4680
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7848 - loss: 0.4151 - val_accuracy: 0.7987 - val_loss: 0.4684
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7568 - loss: 0.4609 - val_accuracy: 0.7987 - val_loss: 0.4684
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7836 - loss: 0.4452 - val_accuracy: 0.7987 - val_loss: 0.4690
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7725 - loss: 0.4403 - val_accuracy: 0.7857 - val_loss: 0.4700
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7704 - loss: 0.4514 - val_accuracy: 0.7987 - val_loss: 0.4692
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7981 - loss: 0.4180 - val_accuracy: 0.8052 - val_loss: 0.4683
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7571 - loss: 0.4485 - val_accuracy: 0.7987 - val_loss: 0.4685
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7936 - loss: 0.4176 - val_accuracy: 0.7987 - val_loss: 0.4682
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7882 - loss: 0.4415 - val_accuracy: 0.7987 - val_loss: 0.4687
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7715 - loss: 0.4332 - val_accuracy: 0.7987 - val_loss: 0.4687
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7792 - loss: 0.4461 - val_accuracy: 0.7987 - val_loss: 0.4681
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7903 - loss: 0.4241 - val_accuracy: 0.7987 - val_loss: 0.4682
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7843 - loss: 0.4110 - val_accuracy: 0.7987 - val_loss: 0.4688
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7655 - loss: 0.4351 - val_accuracy: 0.7987 - val_loss: 0.4697
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7699 - loss: 0.4415 - val_accuracy: 0.7987 - val_loss: 0.4707
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7996 - loss: 0.4073 - val_accuracy: 0.7987 - val_loss: 0.4715
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7934 - loss: 0.4448 - val_accuracy: 0.7987 - val_loss: 0.4719
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7778 - loss: 0.4374 - val_accuracy: 0.7922 - val_loss: 0.4722
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7919 - loss: 0.4270 - val_accuracy: 0.7922 - val_loss: 0.4724
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7778 - loss: 0.4332 - val_accuracy: 0.7987 - val_loss: 0.4723
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7921 - loss: 0.4416 - val_accuracy: 0.7987 - val_loss: 0.4721
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7888 - loss: 0.4436 - val_accuracy: 0.7987 - val_loss: 0.4713
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7950 - loss: 0.4241 - val_accuracy: 0.8052 - val_loss: 0.4720
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7939 - loss: 0.4222 - val_accuracy: 0.7987 - val_loss: 0.4713
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7888 - loss: 0.4298 - val_accuracy: 0.7987 - val_loss: 0.4715
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7827 - loss: 0.4269 - val_accuracy: 0.7922 - val_loss: 0.4710
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7875 - loss: 0.4187 - val_accuracy: 0.7922 - val_loss: 0.4720
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7769 - loss: 0.4533 - val_accuracy: 0.7922 - val_loss: 0.4729
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7714 - loss: 0.4452 - val_accuracy: 0.7922 - val_loss: 0.4724
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7985 - loss: 0.4255 - val_accuracy: 0.7987 - val_loss: 0.4735
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8091 - loss: 0.4221 - val_accuracy: 0.7922 - val_loss: 0.4748
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7986 - loss: 0.4055 - val_accuracy: 0.7987 - val_loss: 0.4747
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8081 - loss: 0.3997 - val_accuracy: 0.7987 - val_loss: 0.4744
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8159 - loss: 0.3775 - val_accuracy: 0.7987 - val_loss: 0.4745
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7928 - loss: 0.4070 - val_accuracy: 0.7857 - val_loss: 0.4733
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7969 - loss: 0.4250 - val_accuracy: 0.7857 - val_loss: 0.4722
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7799 - loss: 0.4226 - val_accuracy: 0.7857 - val_loss: 0.4726
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7822 - loss: 0.4236 - val_accuracy: 0.8052 - val_loss: 0.4738
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7857 - loss: 0.4170 - val_accuracy: 0.8052 - val_loss: 0.4748
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7831 - loss: 0.4195 - val_accuracy: 0.7922 - val_loss: 0.4744
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8459 - loss: 0.3623 - val_accuracy: 0.8052 - val_loss: 0.4753
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8109 - loss: 0.4051 - val_accuracy: 0.7987 - val_loss: 0.4746
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8223 - loss: 0.3777 - val_accuracy: 0.7922 - val_loss: 0.4745
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7920 - loss: 0.4395 - val_accuracy: 0.7922 - val_loss: 0.4753
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7605 - loss: 0.4375 - val_accuracy: 0.7857 - val_loss: 0.4740
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8025 - loss: 0.4118 - val_accuracy: 0.7922 - val_loss: 0.4754
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7995 - loss: 0.4088 - val_accuracy: 0.8052 - val_loss: 0.4750
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7812 - loss: 0.4320 - val_accuracy: 0.8052 - val_loss: 0.4756
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7685 - loss: 0.4657 - val_accuracy: 0.7987 - val_loss: 0.4756

In [ ]:
def build_model(hp):
  model = Sequential()

  units = hp.Int('units',min_value=8,max_value=128,step=8)

  model.add(Dense(units=units, activation='relu', input_dim=8))
  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

  return model

In [ ]:
tuner = kt.RandomSearch(build_model,
                        objective = 'val_accuracy',
                        max_trials = 5,
                        directory = 'mydir')

In [ ]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Trial 5 Complete [00h 00m 04s]
val_accuracy: 0.7402597665786743

Best val_accuracy So Far: 0.8116883039474487
Total elapsed time: 00h 00m 17s

In [ ]:
tuner.get_best_hyperparameters()[0].values

{'units': 72}

In [ ]:
model = tuner.get_best_models(num_models=1)[0]

In [ ]:
history = model.fit(X_train,y_train,epochs=100, initial_epoch=6, validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.7683 - loss: 0.4844 - val_accuracy: 0.8117 - val_loss: 0.4713
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7633 - loss: 0.4866 - val_accuracy: 0.8117 - val_loss: 0.4651
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7587 - loss: 0.4961 - val_accuracy: 0.8182 - val_loss: 0.4624
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7373 - loss: 0.4931 - val_accuracy: 0.8117 - val_loss: 0.4604
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7716 - loss: 0.4634 - val_accuracy: 0.8052 - val_loss: 0.4608
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7904 - loss: 0.4539 - val_accuracy: 0.7987 - val_loss: 0.4610
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7909 - loss: 0.4338 - val_accuracy: 0.8052 - val_loss: 0.4600
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7649 - loss: 0.4726 - val_accuracy: 0.8052 - val_loss: 0.4605
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7504 - loss: 0.4921 - val_accuracy: 0.8052 - val_loss: 0.4596
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8007 - loss: 0.4293 - val_accuracy: 0.8052 - val_loss: 0.4587
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7712 - loss: 0.4557 - val_accuracy: 0.8052 - val_loss: 0.4587
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7860 - loss: 0.4500 - val_accuracy: 0.8052 - val_loss: 0.4602
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7816 - loss: 0.4396 - val_accuracy: 0.7987 - val_loss: 0.4598
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7502 - loss: 0.4890 - val_accuracy: 0.7987 - val_loss: 0.4615
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7706 - loss: 0.4479 - val_accuracy: 0.8117 - val_loss: 0.4625
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7769 - loss: 0.4487 - val_accuracy: 0.7987 - val_loss: 0.4606
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7849 - loss: 0.4321 - val_accuracy: 0.8117 - val_loss: 0.4624
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7676 - loss: 0.4430 - val_accuracy: 0.7987 - val_loss: 0.4626
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7692 - loss: 0.4659 - val_accuracy: 0.8117 - val_loss: 0.4625
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7774 - loss: 0.4411 - val_accuracy: 0.8052 - val_loss: 0.4629
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7834 - loss: 0.4581 - val_accuracy: 0.7987 - val_loss: 0.4620
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7858 - loss: 0.4275 - val_accuracy: 0.7987 - val_loss: 0.4626
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7729 - loss: 0.4566 - val_accuracy: 0.7987 - val_loss: 0.4622
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7764 - loss: 0.4386 - val_accuracy: 0.7987 - val_loss: 0.4637
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7659 - loss: 0.4565 - val_accuracy: 0.7987 - val_loss: 0.4630
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4227 - val_accuracy: 0.7987 - val_loss: 0.4652
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7875 - loss: 0.4144 - val_accuracy: 0.7987 - val_loss: 0.4643
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8087 - loss: 0.4172 - val_accuracy: 0.7922 - val_loss: 0.4654
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7657 - loss: 0.4581 - val_accuracy: 0.7922 - val_loss: 0.4654
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7771 - loss: 0.4400 - val_accuracy: 0.7987 - val_loss: 0.4664
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7927 - loss: 0.4257 - val_accuracy: 0.7922 - val_loss: 0.4656
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7722 - loss: 0.4469 - val_accuracy: 0.7922 - val_loss: 0.4653
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8096 - loss: 0.4019 - val_accuracy: 0.7922 - val_loss: 0.4635
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7838 - loss: 0.4513 - val_accuracy: 0.7922 - val_loss: 0.4641
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7869 - loss: 0.4419 - val_accuracy: 0.7987 - val_loss: 0.4637
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.7829 - loss: 0.4417 - val_accuracy: 0.7922 - val_loss: 0.4644
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7796 - loss: 0.4513 - val_accuracy: 0.8052 - val_loss: 0.4640
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7683 - loss: 0.4452 - val_accuracy: 0.7922 - val_loss: 0.4662
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7931 - loss: 0.4109 - val_accuracy: 0.7922 - val_loss: 0.4659
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7866 - loss: 0.4521 - val_accuracy: 0.7922 - val_loss: 0.4653
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7829 - loss: 0.4332 - val_accuracy: 0.7922 - val_loss: 0.4668
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8052 - loss: 0.4134 - val_accuracy: 0.7857 - val_loss: 0.4673
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7915 - loss: 0.4103 - val_accuracy: 0.7922 - val_loss: 0.4660
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7725 - loss: 0.4567 - val_accuracy: 0.7922 - val_loss: 0.4665
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7813 - loss: 0.4389 - val_accuracy: 0.7857 - val_loss: 0.4655
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8094 - loss: 0.3946 - val_accuracy: 0.7987 - val_loss: 0.4649
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8149 - loss: 0.3994 - val_accuracy: 0.7857 - val_loss: 0.4640
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7890 - loss: 0.4389 - val_accuracy: 0.7922 - val_loss: 0.4635
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8157 - loss: 0.3963 - val_accuracy: 0.7857 - val_loss: 0.4649
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7704 - loss: 0.4479 - val_accuracy: 0.7857 - val_loss: 0.4648
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7758 - loss: 0.4546 - val_accuracy: 0.7857 - val_loss: 0.4655
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7720 - loss: 0.4569 - val_accuracy: 0.7857 - val_loss: 0.4662
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8076 - loss: 0.4135 - val_accuracy: 0.7987 - val_loss: 0.4646
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7741 - loss: 0.4451 - val_accuracy: 0.8052 - val_loss: 0.4634
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8048 - loss: 0.4010 - val_accuracy: 0.8052 - val_loss: 0.4634
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8144 - loss: 0.3898 - val_accuracy: 0.7922 - val_loss: 0.4637
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8029 - loss: 0.3997 - val_accuracy: 0.7987 - val_loss: 0.4633
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7716 - loss: 0.4367 - val_accuracy: 0.7922 - val_loss: 0.4659
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7902 - loss: 0.4299 - val_accuracy: 0.7922 - val_loss: 0.4664
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7839 - loss: 0.4097 - val_accuracy: 0.7922 - val_loss: 0.4665
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7665 - loss: 0.4653 - val_accuracy: 0.7987 - val_loss: 0.4661
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7949 - loss: 0.4511 - val_accuracy: 0.7922 - val_loss: 0.4668
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8033 - loss: 0.4167 - val_accuracy: 0.7922 - val_loss: 0.4659
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7961 - loss: 0.4235 - val_accuracy: 0.7922 - val_loss: 0.4663
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7804 - loss: 0.4289 - val_accuracy: 0.7987 - val_loss: 0.4661
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8279 - loss: 0.3817 - val_accuracy: 0.7987 - val_loss: 0.4661
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7834 - loss: 0.4240 - val_accuracy: 0.7922 - val_loss: 0.4663
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8188 - loss: 0.3939 - val_accuracy: 0.7922 - val_loss: 0.4673
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8103 - loss: 0.3989 - val_accuracy: 0.7987 - val_loss: 0.4681
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7953 - loss: 0.4162 - val_accuracy: 0.7987 - val_loss: 0.4669
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7878 - loss: 0.4136 - val_accuracy: 0.7987 - val_loss: 0.4669
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7668 - loss: 0.4467 - val_accuracy: 0.7922 - val_loss: 0.4680
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7967 - loss: 0.4259 - val_accuracy: 0.7857 - val_loss: 0.4670
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7943 - loss: 0.4159 - val_accuracy: 0.7922 - val_loss: 0.4653
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7960 - loss: 0.4040 - val_accuracy: 0.7987 - val_loss: 0.4680
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8122 - loss: 0.3836 - val_accuracy: 0.7987 - val_loss: 0.4679
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7915 - loss: 0.4246 - val_accuracy: 0.7922 - val_loss: 0.4699
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8018 - loss: 0.4204 - val_accuracy: 0.7857 - val_loss: 0.4676
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7805 - loss: 0.4278 - val_accuracy: 0.7922 - val_loss: 0.4669
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8122 - loss: 0.4029 - val_accuracy: 0.7987 - val_loss: 0.4673
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8029 - loss: 0.4057 - val_accuracy: 0.7987 - val_loss: 0.4664
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8133 - loss: 0.3915 - val_accuracy: 0.7922 - val_loss: 0.4666
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7914 - loss: 0.4306 - val_accuracy: 0.7987 - val_loss: 0.4683
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8084 - loss: 0.3979 - val_accuracy: 0.7922 - val_loss: 0.4678
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8242 - loss: 0.3999 - val_accuracy: 0.7987 - val_loss: 0.4670
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7953 - loss: 0.4220 - val_accuracy: 0.7987 - val_loss: 0.4676
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8245 - loss: 0.3851 - val_accuracy: 0.7987 - val_loss: 0.4675
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7993 - loss: 0.4130 - val_accuracy: 0.7922 - val_loss: 0.4666
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8238 - loss: 0.3979 - val_accuracy: 0.7857 - val_loss: 0.4690
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8050 - loss: 0.4037 - val_accuracy: 0.7922 - val_loss: 0.4698
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7770 - loss: 0.4437 - val_accuracy: 0.7922 - val_loss: 0.4699
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8313 - loss: 0.3793 - val_accuracy: 0.7922 - val_loss: 0.4708
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.8183 - loss: 0.3939 - val_accuracy: 0.7857 - val_loss: 0.4691
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.8207 - loss: 0.3942 - val_accuracy: 0.7922 - val_loss: 0.4702

In [ ]:
def build_model(hp):
  model = Sequential()
  model.add(Dense(72, activation='relu', input_dim=8))
  for  i in range(hp.Int('num_layers', min_value=1, max_value=10)):
    model.add(Dense(72, activation='relu'))
  model.add(Dense(1, activation='sigmoid'))

  model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

  return model

In [ ]:
tuner = kt.RandomSearch(build_model,
                        objective = 'val_accuracy',
                        max_trials = 3,
                        directory='my_dir',
                        project_name = 'num_layers')

In [ ]:
tuner.search(X_train,y_train,epochs=5, validation_data=(X_test,y_test))

Trial 3 Complete [00h 00m 16s]
val_accuracy: 0.8246753215789795

Best val_accuracy So Far: 0.8246753215789795
Total elapsed time: 00h 00m 20s

In [ ]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 9}

In [ ]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 24 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [ ]:
model.fit(X_train,y_train,epochs=100, initial_epoch=6, validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 4s 24ms/step - accuracy: 0.8040 - loss: 0.4299 - val_accuracy: 0.7727 - val_loss: 0.5628
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7912 - loss: 0.4342 - val_accuracy: 0.8052 - val_loss: 0.4949
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8083 - loss: 0.4224 - val_accuracy: 0.7922 - val_loss: 0.4747
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8275 - loss: 0.4065 - val_accuracy: 0.7922 - val_loss: 0.5190
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8061 - loss: 0.4185 - val_accuracy: 0.7013 - val_loss: 0.6061
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8043 - loss: 0.4021 - val_accuracy: 0.7727 - val_loss: 0.5321
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.8414 - loss: 0.3914 - val_accuracy: 0.7792 - val_loss: 0.5145
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8459 - loss: 0.3619 - val_accuracy: 0.7662 - val_loss: 0.5290
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8351 - loss: 0.3811 - val_accuracy: 0.8117 - val_loss: 0.5658
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8513 - loss: 0.3487 - val_accuracy: 0.7078 - val_loss: 0.6153
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8468 - loss: 0.3295 - val_accuracy: 0.7987 - val_loss: 0.5576
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8797 - loss: 0.3013 - val_accuracy: 0.5909 - val_loss: 0.8007
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8127 - loss: 0.4105 - val_accuracy: 0.7208 - val_loss: 0.9448
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8433 - loss: 0.3492 - val_accuracy: 0.7792 - val_loss: 0.5830
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8998 - loss: 0.2509 - val_accuracy: 0.8117 - val_loss: 0.7304
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8939 - loss: 0.2795 - val_accuracy: 0.7857 - val_loss: 0.6132
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8951 - loss: 0.2334 - val_accuracy: 0.7987 - val_loss: 0.7507
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8723 - loss: 0.2733 - val_accuracy: 0.7792 - val_loss: 0.7954
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8909 - loss: 0.2457 - val_accuracy: 0.7532 - val_loss: 0.8260
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9082 - loss: 0.2220 - val_accuracy: 0.7468 - val_loss: 0.7056
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9131 - loss: 0.2298 - val_accuracy: 0.6234 - val_loss: 0.9254
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8676 - loss: 0.3148 - val_accuracy: 0.7662 - val_loss: 0.8061
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9281 - loss: 0.1831 - val_accuracy: 0.6623 - val_loss: 0.8227
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9288 - loss: 0.1764 - val_accuracy: 0.7143 - val_loss: 1.0981
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9009 - loss: 0.2363 - val_accuracy: 0.7208 - val_loss: 0.8994
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9511 - loss: 0.1485 - val_accuracy: 0.7792 - val_loss: 0.9198
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9424 - loss: 0.1480 - val_accuracy: 0.7792 - val_loss: 0.9895
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9413 - loss: 0.1477 - val_accuracy: 0.7597 - val_loss: 1.2958
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9392 - loss: 0.1921 - val_accuracy: 0.7273 - val_loss: 0.9571
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9646 - loss: 0.1110 - val_accuracy: 0.6948 - val_loss: 1.1384
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9548 - loss: 0.1182 - val_accuracy: 0.7013 - val_loss: 1.1797
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9495 - loss: 0.1397 - val_accuracy: 0.7338 - val_loss: 1.3003
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9512 - loss: 0.1187 - val_accuracy: 0.7403 - val_loss: 1.2535
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9428 - loss: 0.1382 - val_accuracy: 0.7208 - val_loss: 1.3792
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9560 - loss: 0.1421 - val_accuracy: 0.7727 - val_loss: 1.2809
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9576 - loss: 0.1177 - val_accuracy: 0.7532 - val_loss: 1.1027
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9707 - loss: 0.0796 - val_accuracy: 0.7338 - val_loss: 1.1847
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9700 - loss: 0.0787 - val_accuracy: 0.7727 - val_loss: 1.3082
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9622 - loss: 0.1001 - val_accuracy: 0.7597 - val_loss: 1.2893
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9550 - loss: 0.1197 - val_accuracy: 0.7208 - val_loss: 1.3695
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9723 - loss: 0.0982 - val_accuracy: 0.7338 - val_loss: 1.5556
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9551 - loss: 0.1324 - val_accuracy: 0.7792 - val_loss: 1.5307
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9782 - loss: 0.0734 - val_accuracy: 0.7208 - val_loss: 1.5035
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9702 - loss: 0.0936 - val_accuracy: 0.7338 - val_loss: 1.2059
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9876 - loss: 0.0459 - val_accuracy: 0.7078 - val_loss: 1.4872
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9750 - loss: 0.0794 - val_accuracy: 0.7338 - val_loss: 1.4541
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9890 - loss: 0.0465 - val_accuracy: 0.6429 - val_loss: 2.3490
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9481 - loss: 0.1664 - val_accuracy: 0.7662 - val_loss: 1.4201
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9829 - loss: 0.0392 - val_accuracy: 0.7013 - val_loss: 1.4556
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9698 - loss: 0.0823 - val_accuracy: 0.7662 - val_loss: 1.5332
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9800 - loss: 0.0582 - val_accuracy: 0.7208 - val_loss: 1.9398
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9863 - loss: 0.0581 - val_accuracy: 0.6364 - val_loss: 2.1307
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9830 - loss: 0.0703 - val_accuracy: 0.7273 - val_loss: 1.8691
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9741 - loss: 0.0811 - val_accuracy: 0.6948 - val_loss: 1.4932
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9752 - loss: 0.0805 - val_accuracy: 0.7597 - val_loss: 1.6632
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9774 - loss: 0.0626 - val_accuracy: 0.7403 - val_loss: 1.6054
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9807 - loss: 0.0440 - val_accuracy: 0.7273 - val_loss: 1.7958
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9832 - loss: 0.0458 - val_accuracy: 0.7143 - val_loss: 1.7640
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9928 - loss: 0.0345 - val_accuracy: 0.6818 - val_loss: 2.0116
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.9885 - loss: 0.0334 - val_accuracy: 0.7208 - val_loss: 1.8125
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9871 - loss: 0.0360 - val_accuracy: 0.7338 - val_loss: 2.2406
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.9877 - loss: 0.0271 - val_accuracy: 0.7273 - val_loss: 2.3234
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9642 - loss: 0.1257 - val_accuracy: 0.7078 - val_loss: 1.7191
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9792 - loss: 0.0418 - val_accuracy: 0.7013 - val_loss: 1.7403
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9780 - loss: 0.0444 - val_accuracy: 0.7468 - val_loss: 1.7511
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9908 - loss: 0.0232 - val_accuracy: 0.7143 - val_loss: 1.7806
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9867 - loss: 0.0395 - val_accuracy: 0.7403 - val_loss: 2.3214
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9945 - loss: 0.0114 - val_accuracy: 0.7208 - val_loss: 2.3547
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9797 - loss: 0.0430 - val_accuracy: 0.7143 - val_loss: 2.0314
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9941 - loss: 0.0183 - val_accuracy: 0.6948 - val_loss: 2.4229
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9874 - loss: 0.0299 - val_accuracy: 0.7273 - val_loss: 2.6013
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9874 - loss: 0.0392 - val_accuracy: 0.7403 - val_loss: 2.6154
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9792 - loss: 0.0713 - val_accuracy: 0.7403 - val_loss: 2.2340
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9911 - loss: 0.0172 - val_accuracy: 0.7273 - val_loss: 2.4107
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9964 - loss: 0.0108 - val_accuracy: 0.6948 - val_loss: 2.6700
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9928 - loss: 0.0284 - val_accuracy: 0.7208 - val_loss: 2.0722
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9828 - loss: 0.0625 - val_accuracy: 0.7143 - val_loss: 2.0151
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9930 - loss: 0.0171 - val_accuracy: 0.6948 - val_loss: 2.1688
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9845 - loss: 0.0477 - val_accuracy: 0.7532 - val_loss: 2.1130
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9966 - loss: 0.0238 - val_accuracy: 0.7662 - val_loss: 2.5697
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9932 - loss: 0.0356 - val_accuracy: 0.7208 - val_loss: 2.1598
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9934 - loss: 0.0386 - val_accuracy: 0.7468 - val_loss: 2.3828
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0022 - val_accuracy: 0.7143 - val_loss: 2.8759
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9830 - loss: 0.0613 - val_accuracy: 0.7532 - val_loss: 2.4077
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9988 - loss: 0.0059 - val_accuracy: 0.7078 - val_loss: 2.5074
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9830 - loss: 0.0642 - val_accuracy: 0.6818 - val_loss: 2.0615
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9852 - loss: 0.0386 - val_accuracy: 0.7727 - val_loss: 2.0807
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9983 - loss: 0.0101 - val_accuracy: 0.7273 - val_loss: 2.3196
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9980 - loss: 0.0065 - val_accuracy: 0.6883 - val_loss: 2.9068
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9761 - loss: 0.1044 - val_accuracy: 0.7468 - val_loss: 2.0181
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9977 - loss: 0.0171 - val_accuracy: 0.7273 - val_loss: 2.0563
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9945 - loss: 0.0106 - val_accuracy: 0.7273 - val_loss: 2.6156
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9997 - loss: 0.0020 - val_accuracy: 0.7273 - val_loss: 2.9771
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9807 - loss: 0.0917 - val_accuracy: 0.7338 - val_loss: 2.7096

In [ ]:
def build_model(hp):
  model= Sequential()

  counter=0
  for i in range(hp.Int('num_layes', min_value=1, max_value=10)):
    if counter==0:

      model.add(
          Dense(
                hp.Int('units'+ str(i), min_value=8, max_value=128, step=8),
                activation=hp.Choice('activation'+ str(i),values=['relu','tanh','sigmoid']),
                input_dim=8
                )
          )
      model.add(Dropout(hp.Choice('dropout'+str(i),values=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))
    else:
      model.add(
          Dense(
              hp.Int('units'+str(i), min_value=8, max_value=128, step=8),
              activation= hp.Choice('activation'+str(i), values=['relu','sigmoid','tanh'])
          )
      )
      model.add(Dropout(hp.Choice('dropout'+str(i),values=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))
    counter+=1
  model.add(
      Dense(
          1,
          activation= 'sigmoid'
      )
  )

  model.compile(optimizer= hp.Choice('optimizer', values=['adam', 'rmsprop','sgd','nadam','adadelta']),
                loss = 'binary_crossentropy',
                metrics = ['accuracy']
                )

  return model

In [ ]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=3,
                        directory='my_dir',
                        project_name = 'final1')

In [ ]:
tuner.search(X_train,y_train, epochs=5, validation_data=(X_test,y_test))

Trial 3 Complete [00h 00m 05s]
val_accuracy: 0.6818181872367859

Best val_accuracy So Far: 0.6818181872367859
Total elapsed time: 00h 00m 16s

In [ ]:
tuner.get_best_hyperparameters()[0].values

{'num_layes': 2,
 'units0': 8,
 'activation0': 'tanh',
 'dropout0': 0.8,
 'optimizer': 'adam',
 'units1': 120,
 'activation1': 'relu',
 'dropout1': 0.1,
 'units2': 120,
 'activation2': 'sigmoid',
 'dropout2': 0.3,
 'units3': 72,
 'activation3': 'relu',
 'dropout3': 0.9,
 'units4': 112,
 'activation4': 'tanh',
 'dropout4': 0.6,
 'units5': 80,
 'activation5': 'sigmoid',
 'dropout5': 0.3,
 'units6': 24,
 'activation6': 'sigmoid',
 'dropout6': 0.9,
 'units7': 16,
 'activation7': 'tanh',
 'dropout7': 0.8}

In [ ]:
model = tuner.get_best_models(num_models=1)[0]

In [ ]:
model.fit(X_train,y_train,epochs=200, initial_epoch=6, validation_data=(X_test,y_test))

Epoch 7/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.6180 - loss: 0.6586 - val_accuracy: 0.6494 - val_loss: 0.6440
Epoch 8/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6650 - loss: 0.6291 - val_accuracy: 0.6494 - val_loss: 0.6302
Epoch 9/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6332 - loss: 0.6590 - val_accuracy: 0.6558 - val_loss: 0.6222
Epoch 10/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6303 - loss: 0.6659 - val_accuracy: 0.6623 - val_loss: 0.6174
Epoch 11/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6587 - loss: 0.6236 - val_accuracy: 0.6753 - val_loss: 0.6065
Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6336 - loss: 0.6398 - val_accuracy: 0.6688 - val_loss: 0.5970
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6591 - loss: 0.6222 - val_accuracy: 0.6948 - val_loss: 0.5865
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6733 - loss: 0.6043 - val_accuracy: 0.7013 - val_loss: 0.5768
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6688 - loss: 0.6177 - val_accuracy: 0.7013 - val_loss: 0.5706
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6687 - loss: 0.6103 - val_accuracy: 0.7273 - val_loss: 0.5633
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6999 - loss: 0.5876 - val_accuracy: 0.7403 - val_loss: 0.5585
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6904 - loss: 0.6042 - val_accuracy: 0.7597 - val_loss: 0.5523
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6539 - loss: 0.6156 - val_accuracy: 0.7727 - val_loss: 0.5444
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6878 - loss: 0.5944 - val_accuracy: 0.7597 - val_loss: 0.5411
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6756 - loss: 0.5818 - val_accuracy: 0.7662 - val_loss: 0.5345
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7356 - loss: 0.5364 - val_accuracy: 0.7597 - val_loss: 0.5258
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7129 - loss: 0.5713 - val_accuracy: 0.7468 - val_loss: 0.5255
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6931 - loss: 0.5592 - val_accuracy: 0.7532 - val_loss: 0.5241
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7001 - loss: 0.6002 - val_accuracy: 0.7532 - val_loss: 0.5244
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6886 - loss: 0.5654 - val_accuracy: 0.7727 - val_loss: 0.5185
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7038 - loss: 0.5820 - val_accuracy: 0.7662 - val_loss: 0.5208
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6940 - loss: 0.5788 - val_accuracy: 0.7597 - val_loss: 0.5225
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7104 - loss: 0.5617 - val_accuracy: 0.7662 - val_loss: 0.5175
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6886 - loss: 0.5648 - val_accuracy: 0.7662 - val_loss: 0.5185
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7192 - loss: 0.5626 - val_accuracy: 0.7597 - val_loss: 0.5195
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7172 - loss: 0.5649 - val_accuracy: 0.7532 - val_loss: 0.5154
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6822 - loss: 0.5741 - val_accuracy: 0.7727 - val_loss: 0.5118
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7077 - loss: 0.5731 - val_accuracy: 0.7532 - val_loss: 0.5140
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7247 - loss: 0.5456 - val_accuracy: 0.7597 - val_loss: 0.5083
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7385 - loss: 0.5344 - val_accuracy: 0.7727 - val_loss: 0.5030
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7232 - loss: 0.5759 - val_accuracy: 0.7532 - val_loss: 0.5063
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7299 - loss: 0.5440 - val_accuracy: 0.7532 - val_loss: 0.5076
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7006 - loss: 0.5901 - val_accuracy: 0.7597 - val_loss: 0.5097
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7151 - loss: 0.5662 - val_accuracy: 0.7597 - val_loss: 0.5120
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7067 - loss: 0.5760 - val_accuracy: 0.7597 - val_loss: 0.5090
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7166 - loss: 0.5540 - val_accuracy: 0.7597 - val_loss: 0.5091
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7268 - loss: 0.5445 - val_accuracy: 0.7662 - val_loss: 0.5074
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7085 - loss: 0.5505 - val_accuracy: 0.7857 - val_loss: 0.5059
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6816 - loss: 0.5903 - val_accuracy: 0.7727 - val_loss: 0.5080
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7408 - loss: 0.5339 - val_accuracy: 0.7662 - val_loss: 0.5048
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7197 - loss: 0.5300 - val_accuracy: 0.7727 - val_loss: 0.5048
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7238 - loss: 0.5291 - val_accuracy: 0.7922 - val_loss: 0.5015
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7025 - loss: 0.5452 - val_accuracy: 0.7857 - val_loss: 0.5000
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6958 - loss: 0.5684 - val_accuracy: 0.7922 - val_loss: 0.5006
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7051 - loss: 0.5596 - val_accuracy: 0.7792 - val_loss: 0.4990
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7178 - loss: 0.5386 - val_accuracy: 0.7792 - val_loss: 0.5015
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7299 - loss: 0.5303 - val_accuracy: 0.7857 - val_loss: 0.4980
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7202 - loss: 0.5435 - val_accuracy: 0.7857 - val_loss: 0.4979
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7330 - loss: 0.5512 - val_accuracy: 0.7857 - val_loss: 0.4997
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7336 - loss: 0.5481 - val_accuracy: 0.7857 - val_loss: 0.4958
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7227 - loss: 0.5454 - val_accuracy: 0.7987 - val_loss: 0.4927
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7089 - loss: 0.5567 - val_accuracy: 0.7857 - val_loss: 0.4956
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7197 - loss: 0.5446 - val_accuracy: 0.7727 - val_loss: 0.5000
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7071 - loss: 0.5683 - val_accuracy: 0.7727 - val_loss: 0.5011
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7061 - loss: 0.5390 - val_accuracy: 0.7792 - val_loss: 0.4970
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7219 - loss: 0.5349 - val_accuracy: 0.7857 - val_loss: 0.4964
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6919 - loss: 0.5470 - val_accuracy: 0.7727 - val_loss: 0.5072
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7304 - loss: 0.5372 - val_accuracy: 0.7727 - val_loss: 0.5035
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7061 - loss: 0.5344 - val_accuracy: 0.7857 - val_loss: 0.4995
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7391 - loss: 0.5331 - val_accuracy: 0.7857 - val_loss: 0.4996
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7298 - loss: 0.5472 - val_accuracy: 0.7857 - val_loss: 0.4982
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7540 - loss: 0.5130 - val_accuracy: 0.7857 - val_loss: 0.4954
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7528 - loss: 0.5300 - val_accuracy: 0.7857 - val_loss: 0.4959
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7312 - loss: 0.5363 - val_accuracy: 0.7727 - val_loss: 0.4989
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7074 - loss: 0.5478 - val_accuracy: 0.7922 - val_loss: 0.5010
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7237 - loss: 0.5291 - val_accuracy: 0.7792 - val_loss: 0.5063
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7223 - loss: 0.5522 - val_accuracy: 0.7792 - val_loss: 0.5011
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7401 - loss: 0.5183 - val_accuracy: 0.7857 - val_loss: 0.4945
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7072 - loss: 0.5492 - val_accuracy: 0.7727 - val_loss: 0.5034
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7358 - loss: 0.5278 - val_accuracy: 0.7792 - val_loss: 0.4982
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6999 - loss: 0.5634 - val_accuracy: 0.7792 - val_loss: 0.5020
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7350 - loss: 0.5558 - val_accuracy: 0.7727 - val_loss: 0.5061
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7189 - loss: 0.5270 - val_accuracy: 0.7727 - val_loss: 0.5029
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7500 - loss: 0.5197 - val_accuracy: 0.7922 - val_loss: 0.5013
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7392 - loss: 0.5250 - val_accuracy: 0.7922 - val_loss: 0.4994
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7210 - loss: 0.5461 - val_accuracy: 0.7922 - val_loss: 0.5008
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7521 - loss: 0.5049 - val_accuracy: 0.7922 - val_loss: 0.4992
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7184 - loss: 0.5334 - val_accuracy: 0.7857 - val_loss: 0.4989
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7476 - loss: 0.5130 - val_accuracy: 0.7727 - val_loss: 0.4940
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7161 - loss: 0.5728 - val_accuracy: 0.7792 - val_loss: 0.4970
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7118 - loss: 0.5560 - val_accuracy: 0.7792 - val_loss: 0.5020
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7402 - loss: 0.5260 - val_accuracy: 0.7922 - val_loss: 0.5001
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7375 - loss: 0.5297 - val_accuracy: 0.7857 - val_loss: 0.4998
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7417 - loss: 0.5380 - val_accuracy: 0.7727 - val_loss: 0.4996
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7372 - loss: 0.5318 - val_accuracy: 0.7792 - val_loss: 0.4996
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7318 - loss: 0.5244 - val_accuracy: 0.7857 - val_loss: 0.4976
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7606 - loss: 0.5074 - val_accuracy: 0.7727 - val_loss: 0.4974
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7275 - loss: 0.5354 - val_accuracy: 0.7857 - val_loss: 0.5006
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6910 - loss: 0.5507 - val_accuracy: 0.7597 - val_loss: 0.5095
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7061 - loss: 0.5618 - val_accuracy: 0.7532 - val_loss: 0.5055
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7312 - loss: 0.5172 - val_accuracy: 0.7792 - val_loss: 0.5013
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7318 - loss: 0.5154 - val_accuracy: 0.7727 - val_loss: 0.5011
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7340 - loss: 0.5324 - val_accuracy: 0.7727 - val_loss: 0.4986
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7364 - loss: 0.5222 - val_accuracy: 0.7792 - val_loss: 0.4968
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7106 - loss: 0.5615 - val_accuracy: 0.7792 - val_loss: 0.4952
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7458 - loss: 0.5353 - val_accuracy: 0.7792 - val_loss: 0.4944
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7300 - loss: 0.5102 - val_accuracy: 0.7792 - val_loss: 0.4972
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7249 - loss: 0.5518 - val_accuracy: 0.7792 - val_loss: 0.4958
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7427 - loss: 0.5288 - val_accuracy: 0.7792 - val_loss: 0.4970
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7599 - loss: 0.5131 - val_accuracy: 0.7727 - val_loss: 0.4975
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7680 - loss: 0.4901 - val_accuracy: 0.7792 - val_loss: 0.4920
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7245 - loss: 0.5122 - val_accuracy: 0.7792 - val_loss: 0.4935
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7254 - loss: 0.5566 - val_accuracy: 0.7792 - val_loss: 0.4975
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7129 - loss: 0.5586 - val_accuracy: 0.7727 - val_loss: 0.4966
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7122 - loss: 0.5306 - val_accuracy: 0.7792 - val_loss: 0.4958
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6911 - loss: 0.5688 - val_accuracy: 0.7792 - val_loss: 0.4974
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7228 - loss: 0.5322 - val_accuracy: 0.7857 - val_loss: 0.4988
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6937 - loss: 0.5408 - val_accuracy: 0.7857 - val_loss: 0.5024
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7469 - loss: 0.4804 - val_accuracy: 0.7792 - val_loss: 0.5011
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7512 - loss: 0.5007 - val_accuracy: 0.7857 - val_loss: 0.4962
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7348 - loss: 0.5298 - val_accuracy: 0.7857 - val_loss: 0.5010
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7474 - loss: 0.5059 - val_accuracy: 0.7857 - val_loss: 0.5004
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7324 - loss: 0.5212 - val_accuracy: 0.7922 - val_loss: 0.4994
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7178 - loss: 0.5517 - val_accuracy: 0.7857 - val_loss: 0.4980
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7356 - loss: 0.5459 - val_accuracy: 0.7857 - val_loss: 0.4993
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7405 - loss: 0.5277 - val_accuracy: 0.7792 - val_loss: 0.5012
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6883 - loss: 0.5308 - val_accuracy: 0.7922 - val_loss: 0.4967
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7208 - loss: 0.5519 - val_accuracy: 0.7857 - val_loss: 0.4997
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7360 - loss: 0.5388 - val_accuracy: 0.7857 - val_loss: 0.4970
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7664 - loss: 0.4961 - val_accuracy: 0.7857 - val_loss: 0.4975
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7398 - loss: 0.5231 - val_accuracy: 0.7857 - val_loss: 0.4990
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7554 - loss: 0.4998 - val_accuracy: 0.7857 - val_loss: 0.5017
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7257 - loss: 0.5210 - val_accuracy: 0.7727 - val_loss: 0.5056
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7309 - loss: 0.5288 - val_accuracy: 0.7792 - val_loss: 0.5053
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7543 - loss: 0.5140 - val_accuracy: 0.7792 - val_loss: 0.5034
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7078 - loss: 0.5159 - val_accuracy: 0.7792 - val_loss: 0.5032
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7355 - loss: 0.5211 - val_accuracy: 0.7857 - val_loss: 0.5002
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7455 - loss: 0.5148 - val_accuracy: 0.7857 - val_loss: 0.4989
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7389 - loss: 0.5373 - val_accuracy: 0.7922 - val_loss: 0.4977
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7256 - loss: 0.5349 - val_accuracy: 0.7987 - val_loss: 0.5002
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7350 - loss: 0.5293 - val_accuracy: 0.7922 - val_loss: 0.5023
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7431 - loss: 0.5156 - val_accuracy: 0.7792 - val_loss: 0.5023
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7298 - loss: 0.5504 - val_accuracy: 0.7792 - val_loss: 0.4996
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7324 - loss: 0.5130 - val_accuracy: 0.7792 - val_loss: 0.4993
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7409 - loss: 0.5302 - val_accuracy: 0.7727 - val_loss: 0.4973
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7374 - loss: 0.5239 - val_accuracy: 0.7857 - val_loss: 0.4993
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7460 - loss: 0.5312 - val_accuracy: 0.7857 - val_loss: 0.5010
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7802 - loss: 0.5111 - val_accuracy: 0.7857 - val_loss: 0.4997
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7114 - loss: 0.5397 - val_accuracy: 0.7792 - val_loss: 0.5010
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7223 - loss: 0.5364 - val_accuracy: 0.7792 - val_loss: 0.4996
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7617 - loss: 0.4920 - val_accuracy: 0.7792 - val_loss: 0.5029
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7194 - loss: 0.5503 - val_accuracy: 0.7857 - val_loss: 0.4992
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7469 - loss: 0.5066 - val_accuracy: 0.7922 - val_loss: 0.4976
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7125 - loss: 0.5655 - val_accuracy: 0.7792 - val_loss: 0.5032
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7374 - loss: 0.5148 - val_accuracy: 0.7857 - val_loss: 0.5020
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7718 - loss: 0.4890 - val_accuracy: 0.7857 - val_loss: 0.4986
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7241 - loss: 0.4973 - val_accuracy: 0.7792 - val_loss: 0.4987
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7574 - loss: 0.4986 - val_accuracy: 0.7792 - val_loss: 0.4958
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7413 - loss: 0.5112 - val_accuracy: 0.7857 - val_loss: 0.4986
Epoch 156/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7622 - loss: 0.4720 - val_accuracy: 0.7792 - val_loss: 0.5063
Epoch 157/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7310 - loss: 0.5218 - val_accuracy: 0.7792 - val_loss: 0.5049
Epoch 158/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7195 - loss: 0.5266 - val_accuracy: 0.7727 - val_loss: 0.5050
Epoch 159/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7478 - loss: 0.5177 - val_accuracy: 0.7792 - val_loss: 0.5090
Epoch 160/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7271 - loss: 0.5129 - val_accuracy: 0.7597 - val_loss: 0.5120
Epoch 161/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7491 - loss: 0.5490 - val_accuracy: 0.7857 - val_loss: 0.5034
Epoch 162/200